<?php

/** @var \Algolia\AlgoliaSearch\Block\Instant\Hit $block */

$priceKey = $block->getPriceKey();

$origFormatedVar = 'price' . $priceKey . '_original_formated';
$tierFormatedVar = 'price' . $priceKey . '_tier_formated';

?>

<script type="text/template" id="instant-hit-template">
    <div class="col-md-12 col-sm-12">
        <div class="result-wrapper" itemprop="itemListElement" itemscope itemtype="http://schema.org/Product">
            <a itemprop="url" href="{{url}}" class="result" data-objectid="{{objectID}}" data-position="{{__position}}">
                <div class="result-content row">
                    <div class="col-xs-5 col-sm-4">
                        <div class="result-thumbnail">
                            {{#image_url}}<img itemprop="image" src="{{{ image_url }}}"/>{{/image_url}}
                            {{^image_url}}<span class="no-image"></span>{{/image_url}}
                        </div>
                    </div>
                    <div class="col-xs-7 col-sm-8">
                        <div class="result-sub-content">
                            <h3 itemprop="name" class="result-title text-ellipsis">
                                {{{ _highlightResult.name.value }}}
                            </h3>

                            <div class="result-content row">
                                <div class="col-xs-8 col-sm-8">
                                    <div class="result-description text-ellipsis">
                                        <span class="product-sku"><?= __('Art-Nr.'); ?>: {{{ _highlightResult.sku.value }}}</span>
                                        {{{ _highlightResult.description.value }}}
                                    </div>
                                </div>
                                <div class="col-xs-4 col-sm-4 text-right" style="position:static">
                                    <div class="ratings">
                                        <div class="result-sub-content">
                                            <div class="product-reviews-summary short" style="display:none">
                                                <div class="rating-summary">
                                                    <span class="label"><span>Rating:</span></span>
                                                    <div class="rating-result" title="{{rating_summary}}%">
                                            <span style="width:{{rating_summary}}%">
                                                <span>{{rating_summary}}%</span>
                                            </span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div itemprop="offers" itemscope itemtype="http://schema.org/AggregateOffer"
                                                 class="price">
                                                <div class="price-wrapper">
                                                    <div>

                                                        <span itemprop="highPrice" class="before_special">{{<?php echo $block->escapeHtml($origFormatedVar); ?>}}</span>

                                                        <span itemprop="lowPrice" class="after_special {{#<?php echo $block->escapeHtml($origFormatedVar); ?>}}promotion{{/<?php echo $block->escapeHtml($origFormatedVar); ?>}}">
                                                            <span class="discount_text"><?php echo __('jetzt nur') ?></span> {{price<?php echo $block->escapeHtml($priceKey); ?>_formated}}</span>
                                                        {{#<?php echo $block->escapeHtml($origFormatedVar); ?>}}

                                                        {{/<?php echo $block->escapeHtml($origFormatedVar); ?>}}
                                                        {{#<?php echo $block->escapeHtml($tierFormatedVar); ?>}}
                                                        <span class="tier_price">
                                                    <?php echo __('As low as') ?>
                                                            <span class="tier_value">{{<?php echo $block->escapeHtml($tierFormatedVar); ?>
                                                                }}</span>
                                                </span>
                                                        {{/<?php echo $block->escapeHtml($tierFormatedVar); ?>}}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    {{#isAddToCartEnabled}}
                                    <form data-role="tocart-form" action="{{ addToCart.action }}" method="post">
                                        <input type="hidden" name="product" value="{{objectID}}">
                                        <input type="hidden" name="uenc" value="{{ addToCart.uenc }}">
                                        <input name="form_key" type="hidden" value="{{ addToCart.formKey }}">
                                        <button type="submit" title="in den Warenkorb" class="action tocart primary"
                                                data-objectid="{{objectID}}" data-position="{{__position}}">
                                            <span>in den Warenkorb</span>
                                        </button>
                                    </form>
                                    {{/isAddToCartEnabled}}

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="algolia-clearfix"></div>
            </a>
        </div>
    </div>
</script>