<?php
$categories = $this->getCategoryCollection();
$display_style = $this->getDisplayStyle();
$category_depth = $this->getCategoryDepth();
$showHeading = $this->showHeading();
?>
<?php if (is_array($showHeading)) :

    ?>
    <h2 class="title"><a
                href="<?= $block->escapeUrl($showHeading['url']); ?>"><span><?= $block->escapeHtml($showHeading['title']); ?></span></a>
    </h2>
<?php endif; ?>

<?= $display_style == 'list' ? '<ul class="list-category">' : ''; ?>

<?php
$i=0;
foreach ($categories as $category):
    if ($display_style == 'footer') : ?><ul class="<?= $display_style == 'footer' ? 'mr-footer-links' : 'list-category'; ?>"><?php endif; ?>
    <li class="nav-<?= $i+1; ?> cat-id-<?= $category->getId(); ?>">
        <?php if ($display_style == 'footer') { ?><strong class="w-title"><?php } ?>
            <a href="<?php echo $block->escapeUrl($category->getUrl()) ?>">

                <?php
                if ($this->showIcon()) {
                    #$catIcon = $this->getCategoryIcon($category->getId());
                    echo '<span class="cat-icon"></span>';
                }
                ?>

                <span class="cat-title"><?php echo $block->escapeHtml($category->getName()) ?></span>
            </a>
            <?php if ($display_style == 'footer') { ?></strong><?php } ?>
    </li>
    <?php if ($category_depth == 2) : ?>

    <?php
    $subcategories = $this->getCategoryChildren($category->getId());
    foreach ($subcategories as $subcategory):
        ?>
        <li>
            <a href="<?php echo $block->escapeUrl($subcategory->getUrl()) ?>">
                <span class="cat-title"><?php echo $block->escapeHtml($subcategory->getName()) ?></span>
            </a>
        </li>
    <?php endforeach; ?>

<?php endif;

    if ($display_style == 'footer') : ?>
        </ul>

    <?php endif; ?>
<?php
    $i++;
endforeach; ?>

<?= $display_style == 'list' ? '</ul>' : ''; ?>