<?php
$_mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');
$_product = $block->getProduct();
?>
<div class="product-info-main-top row">
    <div class="col-6 col-md-5 col-lg-4">
        <?= $this->getChildHtml('product.info.media') ?>
    </div>
    <div class="col-12 col-md-7 col-lg-8">
        <div class="row">
            <div class="col-lg-8">
                <div class=" product-info-main">
                    <div class="row align-items-center">
                        <div class="col-8">
                            <?= $this->getChildHtml('page.main.title') ?>
                            <div class="info-after-title">
                                <?= $this->getChildHtml('product.info.review') ?>
                                <?= $this->getChildHtml('product.info.sku') ?>
                            </div>
                        </div>
                        <div class="col-4">
                            <?= $this->getChildHtml('product.info.addto.wishlist') ?>
                        </div>
                    </div>
                </div>

                <?= $this->getChildHtml('product.info.main') ?>

                <?php if ($_mbHelper->getConfig('mbconfig/product_view/catalog_list')) : ?>
                    <?php
                    $categoryCollection = $_product->getCategoryCollection()->addNameToResult();
                    $catLink = [];
                    foreach ($categoryCollection as $category) {
                        $catLink[] = '<a href="' . $category->getUrl() . '">' . $category->getName() . '</a>';
                    }
                    $countCat = count($catLink);
                    if ($countCat > 1) {
                        $catLable = __('Categories');
                    } else {
                        $catLable = __('Category');
                    }
                    ?>
                    <?php if ($countCat) : ?>
                        <div class="cat-links"><span><?= $catLable ?>
                                : </span><span><?= implode(', ', $catLink) ?></span></div>
                    <?php endif ?>
                <?php endif ?>
            </div>
            <div class="col-lg-4 sns-right">
                <div class="sns-info-box have-border">
                    <div class="info-box-wrapper">
                        <div class="icon">
                            <img src="http://demo.snstheme.com/wp/smarket/wp-content/uploads/2017/02/ico-freeship.png"
                                 alt="Free Shipping">
                        </div>
                        <div class="content-info-box">
                            <h3><a href="#" data-mage-init='{"shipping-modal": {"target": "#shipping-modal"}}'>Kostenlose Lieferung</a></h3>
                            <p>Schon ab <span id="free-shipping-remainder">100 €</span> versandkostenfrei.</p>
                        </div>
                    </div>
                </div>

                <div class="sns-info-box have-border">
                    <div class="info-box-wrapper">
                        <div class="icon">
                            <img src="http://demo.snstheme.com/wp/smarket/wp-content/uploads/2017/02/ico-security.png"
                                 alt="Secure payment">
                        </div>
                        <div class="content-info-box">
                            <h3><a href="#" data-mage-init='{"shipping-modal": {"target": "#payment-modal"}}'>Sichere Bezahlung</a></h3>
                            <p>SSL-Verschlüsselung & Geld-zurück-Garantie</p>
                        </div>
                    </div>
                </div>
                <div class="sns-info-box have-border">
                    <div class="info-box-wrapper">
                        <div class="icon">
                            <img src="http://demo.snstheme.com/wp/smarket/wp-content/uploads/2017/02/ico-supportonline.png"
                                 alt="Support Online">
                        </div>
                        <div class="content-info-box">
                            <h3><a href="#" data-mage-init='{"shipping-modal": {"target": "#customer-satisfaction-modal"}}'>Top Kundenzufriedenheit</a></h3>
                            <p><span id="trusted_shops_rating"><?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('ts_rating')->toHtml();?></span> Sterne sagen alles.</p>
                        </div>
                    </div>
                </div>
                <div class="sns-info-box have-border">
                    <div class="info-box-wrapper">
                        <div class="icon">
                            <img src="http://demo.snstheme.com/wp/smarket/wp-content/uploads/2017/02/ico-payment.png"
                                 alt="Payment on delivery">
                        </div>
                        <div class="content-info-box">
                            <h3><a href="#" data-mage-init='{"shipping-modal": {"target": "#question-modal"}}'>Fragen zum Produkt?</a></h3>
                            <p>Unsere Mitarbeiter helfen Ihnen gerne.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>